### ISSUE TITLE
Adjust offsets on produced jar

### ISSUE THREAD

**Issue by brianm** [brianm/really-executable-jars-maven-plugin#16]
Doing a

```
zip -A target/thething.jar
```

Will properly adjust the offsets on the end record muckery so that the jar stops complaining when being loaded as a jar :-)

**Comment by brianm** [comment]
a few years later, but it looks like commons-compress can [cleanly add preambles](https://github.com/apache/commons-compress/blob/33789f6aa82c7e0576ea918611a484ba410ba08c/src/main/java/org/apache/commons/compress/archivers/zip/ZipArchiveOutputStream.java#L1014) so ... can fix this issue finally!

**Comment by hgschmie** [comment]
should be fixed by the 2.1.0 release (uses the zip-prefixer library to set these prefixes correct).
