### ISSUE TITLE
Output file location for the newly created really executable jar

### ISSUE THREAD

**Issue by dougli1sqrd** [brianm/really-executable-jars-maven-plugin#17]
It would be nice if you could specify a path in the name of the output file, or specify a directory path as a different property altogether so that the finished really executable jar would end up in whatever directory or path. Right now it defaults to target/<really-executable-jar-name>, but I want it to end up in /my/special/path. Am I making sense?

Great plugin! :)

**Comment by brianm** [comment]
I think so, but that is fairly unconventional maven. Would it be better to hook in post-build with another plugin to move things around?

**Comment by dougli1sqrd** [comment]
Ah yeah, that's true, it is unconventional. A post build plugin could work, or a different approach.
