### ISSUE TITLE
Add additional classpath elements

### ISSUE THREAD

**Issue by jdimeo** [brianm/really-executable-jars-maven-plugin#24]
First of all, this little plugin has been a lifesaver to make CLIs that are portable across Mac/Linux (using this) and Windows (using Launch4j). My CLI now has over 100 MB of messy dependencies, and for mostly mysterious reasons it throws an error on the .exe side. I can get it to work if I leave my biggest dependency out of the shaded jar, and tell Launch4j to add an additional classpath element using the `<postCp>` configuration (which adds additional classpath elements). But now, the *nix shaded jar is also missing that dependency.  How hard would it be to add support for that here? or can you help me with writing an extension to the launcher .sh?

**Comment by jdimeo** [comment]
This seems to work, but apparently `realpath` isn't portable? also has duplication (would be ideal if the plugin generated it so it could use the existing `flags` for example)

```sh
#!/bin/sh
SCRIPT_PATH=$(dirname "$(realpath -s "$0")")
exec java --Xmx ... -cp "$SCRIPT_PATH/other-dep.jar:$0" com.domain.MainClass "$@"
```

**Comment by hgschmie** [comment]
I understand your use case, however the goal of this plugin is literally "take a thing that works fine with `java -jar <...>` and turn it into an executable. It seems that your build step is not producing such a jar. The tool does not repack a jar (or add additional things to it) but focuses just on making an existing thing executable.
